### ISSUE TITLE
jade branches not all jade devel

### ISSUE THREAD

**Issue by tkruse** [ros-infrastructure/rosinstall_generator#27]
Not sure where this should be reported. I noticed that the rosinstall file generated by the command:
```
$ rosinstall_generator robot --rosdistro jade --deps --wet-only --upstream-development
```

lists several repositories with branches indigo-devel, or even groovy-devel. I guess this is for repositories having no newer branches, though e.g. message_generation has a jade branch with a new commit.
I saw the same for perception_pcl

Some repositories list 'master' or 'devel' as branch, which seems also strange.

Overall if the naming scheme does not work well because it is common to have the same branch over several distributions, then it might be good to introduce semantic-versioning branchnames instead.

Since this is not a bug, feel free to close without comment.

**Comment by dirk-thomas** [comment]
The branch names are coming from the rosdistro database for each ROS distro, e.g. for Jade: https://github.com/ros/rosdistro/blob/master/jade/distribution.yaml

If there is a "newer" branch in a source repository but the distribution file still lists an "older" branch the maintainer might have forgotten to update it. E.g. for `message_generation` that was the case which I have addressed in https://github.com/ros/rosdistro/commit/3a2a1afefa1f9637d704903622e1b81d7071c872

So for `perception_pcl` you might want to create a ticket at https://github.com/ros-perception/perception_pcl/issues

The best location to report these issues is probably in the issue tracker of the specific repository which uses the wrong branch name.

Regarding the variety of branch names it is basically up to the maintainer to choose what he seems feel "best". There are a few common patterns but at the end of the maintainer has the freedom to choose. If you think it is worth the effort please start an REP to suggest a new branch naming scheme.

Since this is not related to the `rosinstall_generator` I will close the ticket. Please feel free to continue commenting on it.
