### ISSUE TITLE
Broaden support for --tar

### ISSUE THREAD

**Issue by mikepurvis** [ros-infrastructure/rosinstall_generator#30]
The [logic that turns VCS URLs into tarball links](https://github.com/ros-infrastructure/rosinstall_generator/blob/550b74c7d1d9a36a9556af14486d1ac11ba19c22/src/rosinstall_generator/distro.py#L135-L148) is written as generic, but is in fact fairly specific to Github HTTPS URLs. It would be great to support more sophisticated transformations here, including not just supporting Bitbucket HTTPS, but also Github and Bitbucket SSH, and possibly some way to specify a set of additional "user" transformations (for example, for an in-house Stash or Gitlab instance).

I'm happy to work on this, with some design guidance.

**Comment by wjwwood** [comment]
What kind of guidance do you need? I'd say that what ever you do is probably fine so long as the current case continues to work without any extra user input.

**Comment by mikepurvis** [comment]
Mainly, what would be best as a way to get the extra transformations into the tool? Assuming the transformations are a series of regex match/replacement pairs, some options might be:

- pass them in directly by command line (sucks because escaping regexes sucks).
- command-line arg with location of file (sucks because you need a file, and pwd issues).
- env var which contains abs location of file with them. If unset, use a default shipped with the package.
- standard file, eg `/etc/ros/rosinstall_generator/archive_transformations.conf` (sucks because it's a root thing)
- standard .d folder, eg: `/etc/ros/rosinstall_generator/archive_transformations.conf.d` (sucks because it's a root thing, and just seems over the top).

**Comment by mikepurvis** [comment]
Another perhaps less invasive option, would be to simply add a new method to `rosinstall_generator.generator` which registers a tar-transformation function. This kicks down the road the matter of how to expose it to command-line users (env, args, whatever), but anyone doing significant scripting around all this has an easy pathway— just create an in-house wrapper which is aware of the other internal infrastructure.

**Comment by wjwwood** [comment]
Well the first question in my mind (maybe you have a good idea how you'd like to do this already) is how to match a "transformation" to an entry. Naively I'd say you need a map of hosts to transformations. Currently we assume/assert the default transformation happens on urls with github.com as their host. So to augment this capability the basic input should probably be a map of host -> transformation. Since it's likely that there will be multiple host for each transform, you might want to describe the transforms separately from the mapping.

As for how to pass them in, I find it helpful to figure out how to express it (either in yaml or in code) and work on making it convenient from there.

**Comment by dirk-thomas** [comment]
This seems to be addressed by #37.

**Comment by mikepurvis** [comment]
Indeed, fixed by #37.
